version: '3.9'

services:
  db:
    image: postgres-image
    container_name: postgres-db
    environment:
       - POSTGRES_DB=${DB_NAME}
       - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
      
    networks:
      - cloud-network
    volumes:
      - db-volume:/var/lib/postgres/data
    
  web:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud.domain.com
    links:
      - db
    environment:
      - NEXTCLOUD_DB_NAME=${DB_NAME}
      - NEXTCLOUD_DB_USER=${DB_USER}
      - NEXTCLOUD_DB_PASSWORD=${DB_PASSWORD}
      - NEXTCLOUD_DB_HOST=${DB_HOST}
      - NEXTCLOUD_ADMIN_USER=cloud_admin
      - NEXTCLOUD_ADMIN_PASSWORD=cloud_password
      
    networks:
      - cloud-network
    ports:
      - 8080:80
    volumes:
      - cloud-volume:/var/www/html
    depends_on:
      - db


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - cloud-network
    depends_on:
      - db




networks:
    cloud-network:
        driver: bridge

volumes:
    cloud-volume:
    db-volume: